[server]
host = "localhost"
port = "3306"

  [[server.slave]]
  weight = 1
  ip = "10.0.0.1"

  [[server.slave]]
  weight = 5
  ip = "10.0.0.2"

  [[server.slave]]
  weight = 3
  ip = "10.0.0.3"

  # [[server.slave]]
  # weight = 2
  # ip = "10.0.0.4"

[db]
user = "game"
pass = "game"

[kvs]
host = "127.0.0.1"
port = "6379"