[server]
host = "localhost"
port = "3306"

  [[server.slave]]
  weight = 1
  host = "localhost"

  [[server.slave]]
  weight = 1
  host = "localhost"

[db]
user = "game"
pass = "game"

[kvs]
host = "127.0.0.1"
port = "6379"